### DISCUSSION TITLE
I want to use to use SQS, Redis or Rabbit mq for queue

### DISCUSSION THREAD

**Discussion by ashishkpoudel** [blitz-js/blitz#4373] [General]
How do you configure queue worker that run as a separate entry file which will then listen to SQS, Redis or Rabbit mq. This is a very common use case for backend projects and i am not able to find any resources on implementing it.

**Comment by MrLeebo** [comment]
There are a lot of ways to configure your server infrastructure. I couldn't possibly list off all of the ways you might do it. But if you have Docker installed, one way would be to describe your services in a docker-compose.yml file.

```yml
# docker-compose.yml

# WARNING: this is just an example, not meant to be a full, runnable file
services:
  web:
    build:
      context: .
      dockerfile: yourapp/Dockerfile
    ports:
      - "8080:3001"

  # you might use redis for your mq
  redis:
    image: redis

  # or something like localstack to emulate SQS
  sqs:
    image: localstack/localstack
    ports:
      - "4566:4566"

  database:
    image: postgres
```

Then you would be able to build your server environment locally by running `docker compose up` and any hosts that support docker would be able to deploy your application's infrastructure.
