### ISSUE TITLE
DocumentContext is not imported in custom document when installing Material UI recipe

### ISSUE THREAD

**Issue by konradkalemba** [blitz-js/blitz#1248]
### What is the problem?

Material UI recipe modifies `getInitialProps` method of custom document class, however it doesn't add `DocumentContext` to existing import from `blitz` package. Although it doesn't break the app and only raises a TypeScript error, the type should be imported anyway.

I did try to fix this and succeded. The problem is in this line: https://github.com/blitz-js/blitz/blob/canary/recipes/material-ui/index.ts#L54
Instead of `{source: "blitz"}` it should be `{source: {value: "blitz"}}`. This change seems to fix the bug and I can create a PR for this.

### Steps to Reproduce

1. `blitz i material-ui`
2. Check `app/pages/_document.tsx` file

### Versions

```
Windows 10 | win32-x64 | Node: v12.2.0

blitz: 0.23.2 (global)
blitz: 0.23.2 (local)

npmPackages:
  @prisma/cli: 2.8.0 => 2.8.0
  @prisma/client: 2.8.0 => 2.8.0
  blitz: 0.23.2 => 0.23.2
  react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
  react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
  typescript: 4.0.3 => 4.0.3
```

### Other

![image](https://user-images.githubusercontent.com/8682104/95021954-6a0ad580-0674-11eb-8800-9f02eba8ef21.png)
