### ISSUE TITLE
GitHub Action configuration recipe

### ISSUE THREAD

**Issue by tmcw** [blitz-js/blitz#2133]
### What do you want and why?

Blitz has good test defaults, and I'd reckon that most Blitz users will be setting up continuous integration testing. And in 2021, GitHub Actions is a great solution for that - it might be the emerging default?

Setting up GitHub actions my experience tends to be copying-and-pasting code from repo to repo, and then struggling every time I need a service or something complicated. I'm going to be using Blitz with PostgreSQL, so it'll require a service, so the Docker networking and a bunch of other stuff I don't have committed to memory.

I want this to be easier! The basic idea is to provide a default configuration for an actions workflow

### Possible implementation(s)

- A generator might be good, especially if it can look at env files and intelligently include or exclude database drivers.
- Or it could just be a page in documentation
- Or a wiki page

### Additional context

I'm happy to adapt my basic GitHub actions config to the solution:

```yaml
name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install, build, and test
        run: |
          yarn install
          yarn test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/app_test
```
