### ISSUE TITLE
Dependencies missing prevents pnpm working

### ISSUE THREAD

**Issue by vjpr** [blitz-js/blitz#2436]
### What is the problem?

When `blitz` is install as a dev dependency in a project using `pnpm`, there are many dependencies missing.

This is probably because blitz relies on dependency hoisting in `yarn`.

These need to be added:

- minimist
- debug
- tslib
- babylon

### Paste all your error logs here:

```
Error: Cannot find module 'debug'
Require stack:
- /Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/@blitzjs+config@0.36.3/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js
- /Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/@blitzjs+config@0.36.3/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.js
- /Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/@blitzjs+cli@0.36.3_typescript@4.2.4/node_modules/@blitzjs/cli/lib/src/index.js
- /Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/blitz@0.36.3_5567bc033954b9273438214653b4e1b9/node_modules/blitz/cli/dist/blitz-cli.cjs.dev.js
- /Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/blitz@0.36.3_5567bc033954b9273438214653b4e1b9/node_modules/blitz/cli/dist/blitz-cli.cjs.js
```

### Paste all relevant code snippets here:

...

### What are detailed steps to reproduce this?

pnpx 

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.2.0

blitz: 0.36.3 (local)

  Package manager: npm
  System:
    OS: macOS 11.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 409.48 MB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.2.0 - ~/nvm/versions/node/v14.2.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/nvm/versions/node/v14.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.36.3 => 0.36.3
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4```


### Please include below any other applicable logs and screenshots that show your problem:

# Workaround

_.pnpmfile.cjs_

```
  if (pkg.name === 'blitz') {
    pkg.dependencies = {
      ...pkg.dependencies,
      minimist: '*',
      debug: '*',
      tslib: '*',
      babylon: '*',
      semver: '*',
      '@oclif/errors': '*',
      next: '*',
    }
  }
```

**Comment by flybayer** [comment]
`debug` was just added in #2426. And I've just opened https://github.com/blitz-js/blitz/pull/2439 to add `minimist`, `fs-extra`, and `semver`.

The other deps you listed are already included properly as dependencies of `@blitzjs/core` which `blitz` includes.

So test this in the next release and then report back if there's still any issues.

**Comment by flybayer** [comment]
👉 https://github.com/blitz-js/blitz/releases/tag/v0.36.4

**Comment by merceyz** [comment]
> The other deps you listed are already included properly as dependencies of @blitzjs/core which blitz includes.

If what you mean by that is that because `@blitzjs/core` depends on them the others doesn't have to then that's not how it works, see this explainer on hoisting for more details https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies

**Comment by flybayer** [comment]
@merceyz ok yep. What I mean is that the other dependencies aren't not require'd by the `blitz` package itself. They are required in @blitzjs/core or @blitzjs/cli

**Comment by merceyz** [comment]
I tested blitz with Yarn PnP a while ago and again right after making that comment and got to the following list of dependencies before I noticed `blitz` was invoking `npm install` in its postinstall and stopped looking into it so there might be more issues but here are my findings so far.

- All the undeclared dependencies PnP complained about when running `yarn dlx blitz new myAppName`
```yml
packageExtensions:
  "@blitzjs/cli@*":
    dependencies:
      "@blitzjs/config": '*'
      "@blitzjs/generator": '*'
      "@oclif/errors": '*'
      "tslib": '*'
      "debug": '*'
      "globby": '*'
      "@blitzjs/server": '*'
  "@blitzjs/server@*":
    dependencies:
      debug: '*'
  "@blitzjs/config@*":
    dependencies:
      "debug": '*'
  "@blitzjs/display@*":
    dependencies:
      debug: '*'
  "@blitzjs/generator@*":
    dependencies:
      debug: '*'
      prettier: '*'
  "recast@*":
    dependencies:
      babylon: '*'
      "@babel/parser": '*'
  "@oclif/command@*":
    dependencies:
      cli-ux: '*'
      chalk: '*'
  "@oclif/config@*":
    dependencies:
      typescript: '*'
      'fs-extra-debug': '*'
  "@oclif/errors@*":
    dependencies:
      chalk: '*'
```
- The project created by `yarn dlx blitz new myAppName` lacks a dependency on `@blitzjs/server`, `@blitzjs/core`, and `next`
- It tries to require a `.blitz` dependency which it writes to `../node_modules/.blitz` but that should be resolved without using `require`
