### ISSUE TITLE
Deploying Blitz.js in production with Docker fails

### ISSUE THREAD

**Issue by SilvanVerhoeven** [blitz-js/blitz#3714]
### What is the problem?

I want to deploy a Blitz.js in production using Docker. I build and start the containers `docker-compose -f docker-compose.production.yml up --build`. Once the server has started, I open the website via the browser. This fails with an 500 - internal server error. The logs show `Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.` It was generated during the image build, but it seems like Blitz.js wants to access `node_modules/.prisma/...`, which was not copied to the production image (see Dockerfile below).

So I also copy that directory to the production image. Now I get an error for `getCurrentUser()`: `TypeError Cannot read properties of undefined (reading 'userId')` in `.next/server/pages/api/rpc/getCurrentUser.js:27:16`.

It may be worth noting that the Dockerfile works for the development setup.

### Paste all your error logs here:

Without copying `node_modules/.prisma`:

```
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/home/node/app/node_modules/.prisma/client/index.js:3:11)
    at Object.construct (/home/node/app/node_modules/next/dist/stdlib/prisma-utils.js:55:33)
    at Object.3659 (/home/node/app/.next/server/pages/api/rpc/getCurrentUser.js:66:66)
    at __webpack_require__ (/home/node/app/.next/server/webpack-runtime.js:25:42)
    at Object.5459 (/home/node/app/.next/server/pages/api/rpc/getCurrentUser.js:19:60)
    at __webpack_require__ (/home/node/app/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/home/node/app/.next/server/pages/api/rpc/getCurrentUser.js:97:39)
    at /home/node/app/.next/server/pages/api/rpc/getCurrentUser.js:98:28
    at Object.<anonymous> (/home/node/app/.next/server/pages/api/rpc/getCurrentUser.js:101:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

With copying `node_modules/.prisma`:

```
2022-08-12 09:34:11.119 ERROR getCurrentUser() 
TypeError  Cannot read properties of undefined (reading 'userId')
error stack:
• getCurrentUser.js:27 getCurrentUser
    .next/server/pages/api/rpc/getCurrentUser.js:27:16

• api-utils.ts:210 <anonymous>
    node_modules/next/server/api-utils.ts:210:30

• middleware.ts:130 dispatch
    node_modules/next/server/middleware.ts:130:32
 
• middleware.ts:137 <anonymous>
    node_modules/next/server/middleware.ts:137:12

• middleware.ts:64 handleRequestWithMiddleware
     node_modules/next/server/middleware.ts:64:11

• api-utils.ts:25 apiResolver
    node_modules/next/server/api-utils.ts:25:22

• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5

• next-server.js:763 handleApiRequest
    node_modules/next/dist/server/next-server.js:763:9

• next-server.ts:975 fn
    node_modules/next/server/next-server.ts:975:24

• router.ts:347 execute
    node_modules/next/server/router.ts:347:21
```

### Paste all relevant code snippets here:

Dockerfile

```
# Inspired by https://github.com/LoriKarikari/blitz-docker/blob/main/docker/dockerfiles/complete/stretch-slim/Dockerfile

##### Configuration #####

# The Blitz.js App should run here
ARG APP_PORT=3000

# Prisma Studio should run here
ARG STUDIO_PORT=5555

##### Setup #####

# Create a standard base image that has all the defaults
FROM --platform=linux/amd64 node:16-slim as base
ENV NODE_ENV=production
ENV PATH /home/node/app/node_modules/.bin:$PATH
ENV TINI_VERSION v0.19.0
WORKDIR /home/node/app
RUN apt-get update && apt-get install -y openssl --no-install-recommends \
	&& rm -rf /var/lib/apt/lists/* \
	&& chown -R node:node /home/node/app
# Blitz.js recommends using tini, see why: https://github.com/krallin/tini/issues/8
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
USER node
COPY --chown=node:node package*.json yarn.lock* ./
RUN yarn config list && yarn install --frozen-lockfile && yarn cache clean --force

# Create a development image
FROM base as dev
ENV NODE_ENV=development
USER node
COPY --chown=node:node . .
RUN yarn config list && yarn install && yarn cache clean --force
CMD ["bash", "-c", "{ yarn studio & } && yarn dev"]

# Create a testing image
FROM dev as test
ENV NODE_ENV=development
USER node
CMD ["bash", "-c", "yarn lint && yarn test:new"]

# Create a build image
FROM test as build
ENV NODE_ENV=production
USER node
RUN yarn blitz prisma generate && yarn blitz build

# Create a production image
FROM base as prod
ENV NODE_ENV=production
USER node
# Notice the --from:build: We inherent from the base image and use the files from the build image
COPY --chown=node:node --from=build /home/node/app/.next /home/node/app/.next
COPY --chown=node:node --from=build /home/node/app/db /home/node/app/db
# Inserted after first error, otherwise omitted
COPY --chown=node:node --from=build /home/node/app/node_modules/.prisma /home/node/app/node_modules/.prisma
#
EXPOSE ${APP_PORT}
EXPOSE ${STUDIO_PORT}
ENTRYPOINT ["/tini", "--"]
CMD ["bash", "-c", "yarn blitz prisma migrate deploy && { yarn studio & } && yarn start"]
```

`docker-compose.production.yml` (development docker-compose.yml for comparison below):

```
version: "3.8"

services:
  app:
    container_name: proto_app
    build:
      context: .
      target: prod
    image: proto_app:prod
    restart: unless-stopped
    env_file: .env.production # Get DATABASE_URL in case Blitz.js does not already load it
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      - db

  db:
    container_name: proto_db
    image: postgres:14
    restart: unless-stopped
    env_file: .env.production # Get Postgres DB name, user and password
    volumes:
      - proto_db_data:/var/lib/postgresql/data

volumes:
  # Persists DB data. Without, the DB data would be lost every time the db starts up!
  proto_db_data:
```

`getCurrentUser()`:

```
import { User } from "app/types"
import { AuthenticationError, Ctx } from "blitz"
import db from "db"

export default async function getCurrentUser(_ = null, { session }: Ctx): Promise<User> {
  if (!session.userId) throw new AuthenticationError()

  const user = await db.user.findFirst({
    where: { id: session.userId },
    include: { role: true },
  })

  if (!user) throw new AuthenticationError()

  return user
}
```

`docker-compose.yml`:

```
version: "3.8"

services:
  app:
    # On change, also change usage in package.json>scripts>e
    container_name: proto_app
    build:
      context: .
      target: dev
    image: proto_app:dev
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      # Only needed during development: Container gets access to app files on local development machine.
      # Without access, changes made during development would only be reflected
      # every time the container's image is built (hence on every `docker-compose up`).
      - ./:/home/node/app/
    depends_on:
      - db

  db:
    container_name: proto_db
    image: postgres:14
    restart: unless-stopped
    env_file: .env.local # Get Postgres DB name, user and password
    volumes:
      - proto_db_data:/var/lib/postgresql/data

volumes:
  # Persists DB data. Without, the DB data would be lost every time the db starts up!
  proto_db_data:
```

### What are detailed steps to reproduce this?

-

### Run `blitz -v` and paste the output here:

```
yarn run v1.22.19
$ /home/node/app/node_modules/.bin/blitz -v
Linux 5.10 | linux-x64 | Node: v16.16.0

blitz: 0.45.3 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.16 GB / 5.99 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.16.0 - /tmp/yarn--1660297939774-0.28875101016384286/node
    Yarn: 1.22.19 - /tmp/yarn--1660297939774-0.28875101016384286/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.10.0 => 3.10.0 
    blitz: 0.45.3 => 0.45.3 
    prisma: 3.10.0 => 3.10.0 
    react: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020 
    react-dom: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020 
    typescript: ~4.5 => 4.5.5 


Done in 2.09s.
Done in 3.99s.
```
